---

# install:
# git pull the app
# make virtualenv
# pip install dependencies

# deploy:
# git pull the app
# pip install dependencies
# tell supervisor to restart app

- hosts: all
  vars_files:
    - ../vars/common_vars.yml
  become: True
  become_method: sudo  
  tasks:
    - name: Install required system packages.
      apt: pkg={{ item }} state=present install_recommends=yes update-cache=yes
      with_items:
        - acl
        - python-dev
        - gcc
        - python-setuptools
        - python3-pip
        - git-core
        - redis-server
        - libgdal-dev
      tags:
        - install
      notify: 
        - reload redis

    # - name: install gdal 1.11.5 from source
    #   script: ../scripts/gdal_install.sh creates=/usr/bin/gdal-1.11.5
    #   tags:
    #     - install

    - name: create webapps group
      group: name="{{ common_webapps_group }}" state=present
      tags:
        - install

    - name: create webapps user
      user:    
        name: "{{ common_webapps_user }}"
        # need a home dir for pip cache
        createhome: yes
        shell: /bin/bash
        group: "{{ common_webapps_group }}"
        state: present
      tags:
        - install
   
    - name: create our app directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{common_webapps_user}}"
        group: "{{common_webapps_group}}"
        mode: 0755
      with_items:
        - "{{webapps_dir}}"
        - "{{apps_envs_dir}}"
        - "{{app_dir}}"
      tags:
        - install

    - name: pip install virtualenv
      pip:
        executable: pip3
        name: "{{ common_pip_pkgs }}"
        state: present
      tags:
        - install

    - name: set up our app's virtualenv
      command: "virtualenv {{ app_env_name }} -p python2.7"
      args:
        chdir: "{{ apps_envs_dir }}"
        creates: "{{ app_env_name }}/bin/pip"
      become: true
      become_user: "{{common_webapps_user}}"
      tags:
        - install

    # this may not be needed now but originally I didn't create the virtualenv
    # as the webapps user
    - name: webapps user:group own app virtualenv
      command: chown -R {{common_webapps_user}}:{{common_webapps_group}} {{apps_envs_dir}}/{{app_env_name}} 
      tags:
        - install

    - name: git pull project
      git: repo={{repo_url}} dest={{webapps_dir}}/{{app_name}} version=master
      become: true
      become_user: "{{ common_webapps_user }}"        
      tags:
          - install
          - deploy

    - name: install pip requirements for app and restart app processes
      pip: 
        requirements: "{{webapps_dir}}/{{app_name}}/requirements/{{app_deploy_type}}.txt"
        executable: "{{apps_envs_dir}}/{{app_env_name}}/bin/pip"
        chdir: "{{app_dir}}"  # necessary for local package install from requirements 
      notify:
        - reload redis
        - restart celery worker_development
        - restart celery worker_production
        - restart celery beat_development
        - restart celery beat_production
        - restart flask server_development
        - restart flask server_production
      tags:
          - install
          - deploy
      become: true
      become_user: "{{ common_webapps_user }}"

  # probably need to make a task to do this to generate the SHX
  # SHAPE_RESTORE_SHX=YES fio info tweetmapper/src/tweetmapper/prod-states.shp

  handlers:
    - include: handlers.yml
