---

- name: restart app      
  command: "{{item}}"
  args:
      - chdir: "{{app_dir}}"
  with_items:
    - "{{ settings_env_var }} {{ venv_python }} celery -A tasks.celery worker --loglevel=WARN &" 
    - "{{ settings_env_var }} {{ venv_python }} celery -A tasks.celery beat --loglevel=WARN &"
    - "{{ settings_env_var }} {{ venv_python }} manage.py runserver.py &"
  
- name: reload redis
  service: name=redis-server state=restarted