---

- hosts: production
  sudo: true
  vars_files:
  - ../vars/common_vars.yml  
  - ../vars/production_vars.yml
  tasks:
    - name: copy confs to /etc/supervisor/conf.d directory
      template:
        src: ../templates/{{item}}.conf.j2
        dest: "{{ supervisor_confs_dir }}/{{item}}.conf"
        owner: root 
        group: "{{ common_webapps_user }}"
        mode: 0640
      with_items:
        - celeryworker
        - celerybeat
        - gunicorn
      tags:
        - install
        - configure
        - install-supervisor

    - name: start supervisor
      service:
        name: supervisor
        state: restarted
      tags:
        - install
        - configure
        - install-supervisor
