# NOTE THIS IS NOT EVEN COMPLETE YET.  TO DO

#   By default supervisor will be installed into {{ COMMON_APP_DIR }}/supervisor
#   and log to {{ COMMON_LOG_DIR }}/supervisor and run as the
#   {{ common_web_user }}
#
#   The including supervisor with the following parameters
#   will install it into a different location:
#
#    - supervisor_app_dir
#    - supervisor_data_dir
#    - supervisor_log_dir
#    - supervisor_venv_dir
#    - supervisor_service_user
#    - supervisor_service
#
# Dependencies:
#   - common
#
# Example play:
#
#   # Install in the default location,
#   # run as the default user
#
#   roles:
#     - common
#     - role: supervisor
#
#   # Install in an alternate directory
#   # and run as user "foo"
#  - role: supervisor

#
---
- name: create application user
  user: >
    name="{{ supervisor_user }}"
    createhome=no
    shell=/bin/false
  tags:
    - install

- name: create supervisor service user
  user: >
    name="{{ supervisor_service_user }}"
    createhome=no
    shell=/bin/false
  tags:
    - install
    
- name: create supervisor directories
  file: >
    name={{ item }}
    state=directory
    owner={{ supervisor_user }}
    group={{ supervisor_service_user }}
    mode="755"
  with_items:
    - "{{ supervisor_app_dir }}"
    - "{{ supervisor_venv_dir }}"
  tags:
    - install

- name: create service user accessible dirs
  file: >
    name={{ item }}
    state=directory
    owner={{ supervisor_user }}
    group={{ supervisor_service_user }}
    mode="775"
  with_items:
    - "{{ supervisor_cfg_dir }}"
    - "{{ supervisor_available_dir }}"
  tags:
    - install

- name: create supervisor directories
  file: >
    name={{ item }}
    state=directory
    owner={{ supervisor_service_user }}
    group={{ supervisor_user }}
  with_items:
    - "{{ supervisor_data_dir }}"
    - "{{ supervisor_log_dir }}"
  tags:
    - install

- name: install supervisor in its venv
  pip:
    name: supervisor
    version: "{{ supervisor_version }}"
    virtualenv: "{{ supervisor_venv_dir }}"
    state: present
    extra_args: "-i {{ COMMON_PYPI_MIRROR_URL }}"
  sudo_user: "{{ supervisor_user }}"
  tags:
    - install

- name: install supervisor in its venv
  pip: >
    name={{ item }} virtualenv="{{ supervisor_venv_dir }}" state=present
    extra_args="-i {{ COMMON_PYPI_MIRROR_URL }}"
  sudo_user: "{{ supervisor_user }}"
  with_items: supervisor_pip_pkgs
  tags:
    - install

- name: create supervisor master config
  template: >
    src=edx/app/supervisor/supervisord.conf.j2 dest={{ supervisor_cfg }}
    owner={{ supervisor_user }} group={{ supervisor_service_user }}
    mode=0644
  tags:
    - install

- name: start supervisor
  service: >
    name={{ supervisor_service }}
    state=started
  register: start_supervisor
  tags:
    - install

  # calling update on supervisor too soon after it
  # starts will result in an errror.
- name: wait for web port to be available
  wait_for: port={{ supervisor_http_bind_port }} timeout=5
  when: start_supervisor.changed
  tags:
    - install

  # call supervisorctl update every time, this reloads
  # the supervisorctl config
  #
  # we don't use notifications for supervisor because
  # they don't work well with parameterized roles.
  # See https://github.com/ansible/ansible/issues/4853
- name: update supervisor configuration
  shell:  "{{ supervisor_ctl }} -c {{ supervisor_cfg }} update"
  register: supervisor_update
  changed_when: supervisor_update.stdout is defined and supervisor_update.stdout != ""
  tags:
    - install
